

/// Country Code List: ISO 3166-1993 (E)
/// 
/// This international standard provides a two-letter alphabetic code for representing the names of countries, 
/// dependencies, and other areas of special geopolitical interest. 
/// The source of this code set is the "Codes for the Representation of Names of Countries (ISO 3166-1993 (E))."
/// 
/// Note:
/// 
///  2005-04 correction, Nambia --> Namibia.
/// 
/// It is available from: 
/// 
///     American National Standards Institute, Inc.
///     11 West 42nd Street, 13th floor
///     New York, New York 10036
/// 
/// http://xml.coverpages.org/country3166.html
#[derive(Debug, PartialEq, Eq)]
pub enum Country {
    /// Andorra
    AD,
    /// United Arab Emirates
    AE,
    /// Afghanistan
    AF,
    /// Antigua & Barbuda
    AG,
    /// Anguilla
    AI,
    /// Albania
    AL,
    /// Armenia
    AM,
    /// Netherlands Antilles
    AN,
    /// Angola
    AO,
    /// Antarctica
    AQ,
    /// Argentina
    AR,
    /// American Samoa
    AS,
    /// Austria
    AT,
    /// Australia
    AU,
    /// Aruba
    AW,
    /// Azerbaijan
    AZ,
    /// Bosnia and Herzegovina
    BA,
    /// Barbados
    BB,
    /// Bangladesh
    BD,
    /// Belgium
    BE,
    /// Burkina Faso
    BF,
    /// Bulgaria
    BG,
    /// Bahrain
    BH,
    /// Burundi
    BI,
    /// Benin
    BJ,
    /// Bermuda
    BM,
    /// Brunei Darussalam
    BN,
    /// Bolivia
    BO,
    /// Brazil
    BR,
    /// Bahama
    BS,
    /// Bhutan
    BT,
    /// Burma (no longer exists)
    BU,
    /// Bouvet Island
    BV,
    /// Botswana
    BW,
    /// Belarus
    BY,
    /// Belize
    BZ,
    /// Canada
    CA,
    /// Cocos (Keeling) Islands
    CC,
    /// Central African Republic
    CF,
    /// Congo
    CG,
    /// Switzerland
    CH,
    /// Côte D'ivoire (Ivory Coast)
    CI,
    /// Cook Iislands
    CK,
    /// Chile
    CL,
    /// Cameroon
    CM,
    /// China
    CN,
    /// Colombia
    CO,
    /// Costa Rica
    CR,
    /// Czechoslovakia (no longer exists)
    CS,
    /// Cuba
    CU,
    /// Cape Verde
    CV,
    /// Christmas Island
    CX,
    /// Cyprus
    CY,
    /// Czech Republic
    CZ,
    /// German Democratic Republic (no longer exists)
    DD,
    /// Germany
    DE,
    /// Djibouti
    DJ,
    /// Denmark
    DK,
    /// Dominica
    DM,
    /// Dominican Republic
    DO,
    /// Algeria
    DZ,
    /// Ecuador
    EC,
    /// Estonia
    EE,
    /// Egypt
    EG,
    /// Western Sahara
    EH,
    /// Eritrea
    ER,
    /// Spain
    ES,
    /// Ethiopia
    ET,
    /// Finland
    FI,
    /// Fiji
    FJ,
    /// Falkland Islands (Malvinas)
    FK,
    /// Micronesia
    FM,
    /// Faroe Islands
    FO,
    /// France
    FR,
    /// France, Metropolitan
    FX,
    /// Gabon
    GA,
    /// United Kingdom (Great Britain)
    GB,
    /// Grenada
    GD,
    /// Georgia
    GE,
    /// French Guiana
    GF,
    /// Ghana
    GH,
    /// Gibraltar
    GI,
    /// Greenland
    GL,
    /// Gambia
    GM,
    /// Guinea
    GN,
    /// Guadeloupe
    GP,
    /// Equatorial Guinea
    GQ,
    /// Greece
    GR,
    /// South Georgia and the South Sandwich Islands
    GS,
    /// Guatemala
    GT,
    /// Guam
    GU,
    /// Guinea-Bissau
    GW,
    /// Guyana
    GY,
    /// Hong Kong
    HK,
    /// Heard & McDonald Islands
    HM,
    /// Honduras
    HN,
    /// Croatia
    HR,
    /// Haiti
    HT,
    /// Hungary
    HU,
    /// Indonesia
    ID,
    /// Ireland
    IE,
    /// Israel
    IL,
    /// India
    IN,
    /// British Indian Ocean Territory
    IO,
    /// Iraq
    IQ,
    /// Islamic Republic of Iran
    IR,
    /// Iceland
    IS,
    /// Italy
    IT,
    /// Jamaica
    JM,
    /// Jordan
    JO,
    /// Japan
    JP,
    /// Kenya
    KE,
    /// Kyrgyzstan
    KG,
    /// Cambodia
    KH,
    /// Kiribati
    KI,
    /// Comoros
    KM,
    /// St. Kitts and Nevis
    KN,
    /// Korea, Democratic People's Republic of
    KP,
    /// Korea, Republic of
    KR,
    /// Kuwait
    KW,
    /// Cayman Islands
    KY,
    /// Kazakhstan
    KZ,
    /// Lao People's Democratic Republic
    LA,
    /// Lebanon
    LB,
    /// Saint Lucia
    LC,
    /// Liechtenstein
    LI,
    /// Sri Lanka
    LK,
    /// Liberia
    LR,
    /// Lesotho
    LS,
    /// Lithuania
    LT,
    /// Luxembourg
    LU,
    /// Latvia
    LV,
    /// Libyan Arab Jamahiriya
    LY,
    /// Morocco
    MA,
    /// Monaco
    MC,
    /// Moldova, Republic of
    MD,
    /// Madagascar
    MG,
    /// Marshall Islands
    MH,
    /// Mali
    ML,
    /// Mongolia
    MN,
    /// Myanmar
    MM,
    /// Macau
    MO,
    /// Northern Mariana Islands
    MP,
    /// Martinique
    MQ,
    /// Mauritania
    MR,
    /// Monserrat
    MS,
    /// Malta
    MT,
    /// Mauritius
    MU,
    /// Maldives
    MV,
    /// Malawi
    MW,
    /// Mexico
    MX,
    /// Malaysia
    MY,
    /// Mozambique
    MZ,
    /// Namibia
    NA,
    /// New Caledonia
    NC,
    /// Niger
    NE,
    /// Norfolk Island
    NF,
    /// Nigeria
    NG,
    /// Nicaragua
    NI,
    /// Netherlands
    NL,
    /// Norway
    NO,
    /// Nepal
    NP,
    /// Nauru
    NR,
    /// Neutral Zone (no longer exists)
    NT,
    /// Niue
    NU,
    /// New Zealand
    NZ,
    /// Oman
    OM,
    /// Panama
    PA,
    /// Peru
    PE,
    /// French Polynesia
    PF,
    /// Papua New Guinea
    PG,
    /// Philippines
    PH,
    /// Pakistan
    PK,
    /// Poland
    PL,
    /// St. Pierre & Miquelon
    PM,
    /// Pitcairn
    PN,
    /// Puerto Rico
    PR,
    /// Portugal
    PT,
    /// Palau
    PW,
    /// Paraguay
    PY,
    /// Qatar
    QA,
    /// Réunion
    RE,
    /// Romania
    RO,
    /// Russian Federation
    RU,
    /// Rwanda
    RW,
    /// Saudi Arabia
    SA,
    /// Solomon Islands
    SB,
    /// Seychelles
    SC,
    /// Sudan
    SD,
    /// Sweden
    SE,
    /// Singapore
    SG,
    /// St. Helena
    SH,
    /// Slovenia
    SI,
    /// Svalbard & Jan Mayen Islands
    SJ,
    /// Slovakia
    SK,
    /// Sierra Leone
    SL,
    /// San Marino
    SM,
    /// Senegal
    SN,
    /// Somalia
    SO,
    /// Suriname
    SR,
    /// Sao Tome & Principe
    ST,
    /// Union of Soviet Socialist Republics (no longer exists)
    SU,
    /// El Salvador
    SV,
    /// Syrian Arab Republic
    SY,
    /// Swaziland
    SZ,
    /// Turks & Caicos Islands
    TC,
    /// Chad
    TD,
    /// French Southern Territories
    TF,
    /// Togo
    TG,
    /// Thailand
    TH,
    /// Tajikistan
    TJ,
    /// Tokelau
    TK,
    /// Turkmenistan
    TM,
    /// Tunisia
    TN,
    /// Tonga
    TO,
    /// East Timor
    TP,
    /// Turkey
    TR,
    /// Trinidad & Tobago
    TT,
    /// Tuvalu
    TV,
    /// Taiwan, Province of China
    TW,
    /// Tanzania, United Republic of
    TZ,
    /// Ukraine
    UA,
    /// Uganda
    UG,
    /// United States Minor Outlying Islands
    UM,
    /// United States of America
    US,
    /// Uruguay
    UY,
    /// Uzbekistan
    UZ,
    /// Vatican City State (Holy See)
    VA,
    /// St. Vincent & the Grenadines
    VC,
    /// Venezuela
    VE,
    /// British Virgin Islands
    VG,
    /// United States Virgin Islands
    VI,
    /// Viet Nam
    VN,
    /// Vanuatu
    VU,
    /// Wallis & Futuna Islands
    WF,
    /// Samoa
    WS,
    /// Democratic Yemen (no longer exists)
    YD,
    /// Yemen
    YE,
    /// Mayotte
    YT,
    /// Yugoslavia
    YU,
    /// South Africa
    ZA,
    /// Zambia
    ZM,
    /// Zaire
    ZR,
    /// Zimbabwe
    ZW,
    /// Unknown or unspecified country
    ZZ,
}


impl Country {
    pub fn from_index(index: u8) -> Result<Self, &'static str>{
        match index {
            0 => Ok(Country::AD), 
            1 => Ok(Country::AE), 
            2 => Ok(Country::AF), 
            3 => Ok(Country::AG), 
            4 => Ok(Country::AI), 
            5 => Ok(Country::AL), 
            6 => Ok(Country::AM), 
            7 => Ok(Country::AN), 
            8 => Ok(Country::AO), 
            9 => Ok(Country::AQ), 
            10 => Ok(Country::AR), 
            11 => Ok(Country::AS), 
            12 => Ok(Country::AT), 
            13 => Ok(Country::AU), 
            14 => Ok(Country::AW), 
            15 => Ok(Country::AZ), 
            16 => Ok(Country::BA), 
            17 => Ok(Country::BB), 
            18 => Ok(Country::BD), 
            19 => Ok(Country::BE), 
            20 => Ok(Country::BF), 
            21 => Ok(Country::BG), 
            22 => Ok(Country::BH), 
            23 => Ok(Country::BI), 
            24 => Ok(Country::BJ), 
            25 => Ok(Country::BM), 
            26 => Ok(Country::BN), 
            27 => Ok(Country::BO), 
            28 => Ok(Country::BR), 
            29 => Ok(Country::BS), 
            30 => Ok(Country::BT), 
            31 => Ok(Country::BU), 
            32 => Ok(Country::BV), 
            33 => Ok(Country::BW), 
            34 => Ok(Country::BY), 
            35 => Ok(Country::BZ), 
            36 => Ok(Country::CA), 
            37 => Ok(Country::CC), 
            38 => Ok(Country::CF), 
            39 => Ok(Country::CG), 
            40 => Ok(Country::CH), 
            41 => Ok(Country::CI), 
            42 => Ok(Country::CK), 
            43 => Ok(Country::CL), 
            44 => Ok(Country::CM), 
            45 => Ok(Country::CN), 
            46 => Ok(Country::CO), 
            47 => Ok(Country::CR), 
            48 => Ok(Country::CS), 
            49 => Ok(Country::CU), 
            50 => Ok(Country::CV), 
            51 => Ok(Country::CX), 
            52 => Ok(Country::CY), 
            53 => Ok(Country::CZ), 
            54 => Ok(Country::DD), 
            55 => Ok(Country::DE), 
            56 => Ok(Country::DJ), 
            57 => Ok(Country::DK), 
            58 => Ok(Country::DM), 
            59 => Ok(Country::DO), 
            60 => Ok(Country::DZ), 
            61 => Ok(Country::EC), 
            62 => Ok(Country::EE), 
            63 => Ok(Country::EG), 
            64 => Ok(Country::EH), 
            65 => Ok(Country::ER), 
            66 => Ok(Country::ES), 
            67 => Ok(Country::ET), 
            68 => Ok(Country::FI), 
            69 => Ok(Country::FJ), 
            70 => Ok(Country::FK), 
            71 => Ok(Country::FM), 
            72 => Ok(Country::FO), 
            73 => Ok(Country::FR), 
            74 => Ok(Country::FX), 
            75 => Ok(Country::GA), 
            76 => Ok(Country::GB), 
            77 => Ok(Country::GD), 
            78 => Ok(Country::GE), 
            79 => Ok(Country::GF), 
            80 => Ok(Country::GH), 
            81 => Ok(Country::GI), 
            82 => Ok(Country::GL), 
            83 => Ok(Country::GM), 
            84 => Ok(Country::GN), 
            85 => Ok(Country::GP), 
            86 => Ok(Country::GQ), 
            87 => Ok(Country::GR), 
            88 => Ok(Country::GS), 
            89 => Ok(Country::GT), 
            90 => Ok(Country::GU), 
            91 => Ok(Country::GW), 
            92 => Ok(Country::GY), 
            93 => Ok(Country::HK), 
            94 => Ok(Country::HM), 
            95 => Ok(Country::HN), 
            96 => Ok(Country::HR), 
            97 => Ok(Country::HT), 
            98 => Ok(Country::HU), 
            99 => Ok(Country::ID), 
            100 => Ok(Country::IE), 
            101 => Ok(Country::IL), 
            102 => Ok(Country::IN), 
            103 => Ok(Country::IO), 
            104 => Ok(Country::IQ), 
            105 => Ok(Country::IR), 
            106 => Ok(Country::IS), 
            107 => Ok(Country::IT), 
            108 => Ok(Country::JM), 
            109 => Ok(Country::JO), 
            110 => Ok(Country::JP), 
            111 => Ok(Country::KE), 
            112 => Ok(Country::KG), 
            113 => Ok(Country::KH), 
            114 => Ok(Country::KI), 
            115 => Ok(Country::KM), 
            116 => Ok(Country::KN), 
            117 => Ok(Country::KP), 
            118 => Ok(Country::KR), 
            119 => Ok(Country::KW), 
            120 => Ok(Country::KY), 
            121 => Ok(Country::KZ), 
            122 => Ok(Country::LA), 
            123 => Ok(Country::LB), 
            124 => Ok(Country::LC), 
            125 => Ok(Country::LI), 
            126 => Ok(Country::LK), 
            127 => Ok(Country::LR), 
            128 => Ok(Country::LS), 
            129 => Ok(Country::LT), 
            130 => Ok(Country::LU), 
            131 => Ok(Country::LV), 
            132 => Ok(Country::LY), 
            133 => Ok(Country::MA), 
            134 => Ok(Country::MC), 
            135 => Ok(Country::MD), 
            136 => Ok(Country::MG), 
            137 => Ok(Country::MH), 
            138 => Ok(Country::ML), 
            139 => Ok(Country::MN), 
            140 => Ok(Country::MM), 
            141 => Ok(Country::MO), 
            142 => Ok(Country::MP), 
            143 => Ok(Country::MQ), 
            144 => Ok(Country::MR), 
            145 => Ok(Country::MS), 
            146 => Ok(Country::MT), 
            147 => Ok(Country::MU), 
            148 => Ok(Country::MV), 
            149 => Ok(Country::MW), 
            150 => Ok(Country::MX), 
            151 => Ok(Country::MY), 
            152 => Ok(Country::MZ), 
            153 => Ok(Country::NA), 
            154 => Ok(Country::NC), 
            155 => Ok(Country::NE), 
            156 => Ok(Country::NF), 
            157 => Ok(Country::NG), 
            158 => Ok(Country::NI), 
            159 => Ok(Country::NL), 
            160 => Ok(Country::NO), 
            161 => Ok(Country::NP), 
            162 => Ok(Country::NR), 
            163 => Ok(Country::NT), 
            164 => Ok(Country::NU), 
            165 => Ok(Country::NZ), 
            166 => Ok(Country::OM), 
            167 => Ok(Country::PA), 
            168 => Ok(Country::PE), 
            169 => Ok(Country::PF), 
            170 => Ok(Country::PG), 
            171 => Ok(Country::PH), 
            172 => Ok(Country::PK), 
            173 => Ok(Country::PL), 
            174 => Ok(Country::PM), 
            175 => Ok(Country::PN), 
            176 => Ok(Country::PR), 
            177 => Ok(Country::PT), 
            178 => Ok(Country::PW), 
            179 => Ok(Country::PY), 
            180 => Ok(Country::QA), 
            181 => Ok(Country::RE), 
            182 => Ok(Country::RO), 
            183 => Ok(Country::RU), 
            184 => Ok(Country::RW), 
            185 => Ok(Country::SA), 
            186 => Ok(Country::SB), 
            187 => Ok(Country::SC), 
            188 => Ok(Country::SD), 
            189 => Ok(Country::SE), 
            190 => Ok(Country::SG), 
            191 => Ok(Country::SH), 
            192 => Ok(Country::SI), 
            193 => Ok(Country::SJ), 
            194 => Ok(Country::SK), 
            195 => Ok(Country::SL), 
            196 => Ok(Country::SM), 
            197 => Ok(Country::SN), 
            198 => Ok(Country::SO), 
            199 => Ok(Country::SR), 
            200 => Ok(Country::ST), 
            201 => Ok(Country::SU), 
            202 => Ok(Country::SV), 
            203 => Ok(Country::SY), 
            204 => Ok(Country::SZ), 
            205 => Ok(Country::TC), 
            206 => Ok(Country::TD), 
            207 => Ok(Country::TF), 
            208 => Ok(Country::TG), 
            209 => Ok(Country::TH), 
            210 => Ok(Country::TJ), 
            211 => Ok(Country::TK), 
            212 => Ok(Country::TM), 
            213 => Ok(Country::TN), 
            214 => Ok(Country::TO), 
            215 => Ok(Country::TP), 
            216 => Ok(Country::TR), 
            217 => Ok(Country::TT), 
            218 => Ok(Country::TV), 
            219 => Ok(Country::TW), 
            220 => Ok(Country::TZ), 
            221 => Ok(Country::UA), 
            222 => Ok(Country::UG), 
            223 => Ok(Country::UM), 
            224 => Ok(Country::US), 
            225 => Ok(Country::UY), 
            226 => Ok(Country::UZ), 
            227 => Ok(Country::VA), 
            228 => Ok(Country::VC), 
            229 => Ok(Country::VE), 
            230 => Ok(Country::VG), 
            231 => Ok(Country::VI), 
            232 => Ok(Country::VN), 
            233 => Ok(Country::VU), 
            234 => Ok(Country::WF), 
            235 => Ok(Country::WS), 
            236 => Ok(Country::YD), 
            237 => Ok(Country::YE), 
            238 => Ok(Country::YT), 
            239 => Ok(Country::YU), 
            240 => Ok(Country::ZA), 
            241 => Ok(Country::ZM), 
            242 => Ok(Country::ZR), 
            243 => Ok(Country::ZW), 
            244 => Ok(Country::ZZ), 
            _ => Err("Oh, no ...") 
        }
    }

    pub fn from_code(code: &str) -> Result<Self, &'static str>{
        match code {
            "AD" => Ok(Country::AD), 
            "AE" => Ok(Country::AE), 
            "AF" => Ok(Country::AF), 
            "AG" => Ok(Country::AG), 
            "AI" => Ok(Country::AI), 
            "AL" => Ok(Country::AL), 
            "AM" => Ok(Country::AM), 
            "AN" => Ok(Country::AN), 
            "AO" => Ok(Country::AO), 
            "AQ" => Ok(Country::AQ), 
            "AR" => Ok(Country::AR), 
            "AS" => Ok(Country::AS), 
            "AT" => Ok(Country::AT), 
            "AU" => Ok(Country::AU), 
            "AW" => Ok(Country::AW), 
            "AZ" => Ok(Country::AZ), 
            "BA" => Ok(Country::BA), 
            "BB" => Ok(Country::BB), 
            "BD" => Ok(Country::BD), 
            "BE" => Ok(Country::BE), 
            "BF" => Ok(Country::BF), 
            "BG" => Ok(Country::BG), 
            "BH" => Ok(Country::BH), 
            "BI" => Ok(Country::BI), 
            "BJ" => Ok(Country::BJ), 
            "BM" => Ok(Country::BM), 
            "BN" => Ok(Country::BN), 
            "BO" => Ok(Country::BO), 
            "BR" => Ok(Country::BR), 
            "BS" => Ok(Country::BS), 
            "BT" => Ok(Country::BT), 
            "BU" => Ok(Country::BU), 
            "BV" => Ok(Country::BV), 
            "BW" => Ok(Country::BW), 
            "BY" => Ok(Country::BY), 
            "BZ" => Ok(Country::BZ), 
            "CA" => Ok(Country::CA), 
            "CC" => Ok(Country::CC), 
            "CF" => Ok(Country::CF), 
            "CG" => Ok(Country::CG), 
            "CH" => Ok(Country::CH), 
            "CI" => Ok(Country::CI), 
            "CK" => Ok(Country::CK), 
            "CL" => Ok(Country::CL), 
            "CM" => Ok(Country::CM), 
            "CN" => Ok(Country::CN), 
            "CO" => Ok(Country::CO), 
            "CR" => Ok(Country::CR), 
            "CS" => Ok(Country::CS), 
            "CU" => Ok(Country::CU), 
            "CV" => Ok(Country::CV), 
            "CX" => Ok(Country::CX), 
            "CY" => Ok(Country::CY), 
            "CZ" => Ok(Country::CZ), 
            "DD" => Ok(Country::DD), 
            "DE" => Ok(Country::DE), 
            "DJ" => Ok(Country::DJ), 
            "DK" => Ok(Country::DK), 
            "DM" => Ok(Country::DM), 
            "DO" => Ok(Country::DO), 
            "DZ" => Ok(Country::DZ), 
            "EC" => Ok(Country::EC), 
            "EE" => Ok(Country::EE), 
            "EG" => Ok(Country::EG), 
            "EH" => Ok(Country::EH), 
            "ER" => Ok(Country::ER), 
            "ES" => Ok(Country::ES), 
            "ET" => Ok(Country::ET), 
            "FI" => Ok(Country::FI), 
            "FJ" => Ok(Country::FJ), 
            "FK" => Ok(Country::FK), 
            "FM" => Ok(Country::FM), 
            "FO" => Ok(Country::FO), 
            "FR" => Ok(Country::FR), 
            "FX" => Ok(Country::FX), 
            "GA" => Ok(Country::GA), 
            "GB" => Ok(Country::GB), 
            "GD" => Ok(Country::GD), 
            "GE" => Ok(Country::GE), 
            "GF" => Ok(Country::GF), 
            "GH" => Ok(Country::GH), 
            "GI" => Ok(Country::GI), 
            "GL" => Ok(Country::GL), 
            "GM" => Ok(Country::GM), 
            "GN" => Ok(Country::GN), 
            "GP" => Ok(Country::GP), 
            "GQ" => Ok(Country::GQ), 
            "GR" => Ok(Country::GR), 
            "GS" => Ok(Country::GS), 
            "GT" => Ok(Country::GT), 
            "GU" => Ok(Country::GU), 
            "GW" => Ok(Country::GW), 
            "GY" => Ok(Country::GY), 
            "HK" => Ok(Country::HK), 
            "HM" => Ok(Country::HM), 
            "HN" => Ok(Country::HN), 
            "HR" => Ok(Country::HR), 
            "HT" => Ok(Country::HT), 
            "HU" => Ok(Country::HU), 
            "ID" => Ok(Country::ID), 
            "IE" => Ok(Country::IE), 
            "IL" => Ok(Country::IL), 
            "IN" => Ok(Country::IN), 
            "IO" => Ok(Country::IO), 
            "IQ" => Ok(Country::IQ), 
            "IR" => Ok(Country::IR), 
            "IS" => Ok(Country::IS), 
            "IT" => Ok(Country::IT), 
            "JM" => Ok(Country::JM), 
            "JO" => Ok(Country::JO), 
            "JP" => Ok(Country::JP), 
            "KE" => Ok(Country::KE), 
            "KG" => Ok(Country::KG), 
            "KH" => Ok(Country::KH), 
            "KI" => Ok(Country::KI), 
            "KM" => Ok(Country::KM), 
            "KN" => Ok(Country::KN), 
            "KP" => Ok(Country::KP), 
            "KR" => Ok(Country::KR), 
            "KW" => Ok(Country::KW), 
            "KY" => Ok(Country::KY), 
            "KZ" => Ok(Country::KZ), 
            "LA" => Ok(Country::LA), 
            "LB" => Ok(Country::LB), 
            "LC" => Ok(Country::LC), 
            "LI" => Ok(Country::LI), 
            "LK" => Ok(Country::LK), 
            "LR" => Ok(Country::LR), 
            "LS" => Ok(Country::LS), 
            "LT" => Ok(Country::LT), 
            "LU" => Ok(Country::LU), 
            "LV" => Ok(Country::LV), 
            "LY" => Ok(Country::LY), 
            "MA" => Ok(Country::MA), 
            "MC" => Ok(Country::MC), 
            "MD" => Ok(Country::MD), 
            "MG" => Ok(Country::MG), 
            "MH" => Ok(Country::MH), 
            "ML" => Ok(Country::ML), 
            "MN" => Ok(Country::MN), 
            "MM" => Ok(Country::MM), 
            "MO" => Ok(Country::MO), 
            "MP" => Ok(Country::MP), 
            "MQ" => Ok(Country::MQ), 
            "MR" => Ok(Country::MR), 
            "MS" => Ok(Country::MS), 
            "MT" => Ok(Country::MT), 
            "MU" => Ok(Country::MU), 
            "MV" => Ok(Country::MV), 
            "MW" => Ok(Country::MW), 
            "MX" => Ok(Country::MX), 
            "MY" => Ok(Country::MY), 
            "MZ" => Ok(Country::MZ), 
            "NA" => Ok(Country::NA), 
            "NC" => Ok(Country::NC), 
            "NE" => Ok(Country::NE), 
            "NF" => Ok(Country::NF), 
            "NG" => Ok(Country::NG), 
            "NI" => Ok(Country::NI), 
            "NL" => Ok(Country::NL), 
            "NO" => Ok(Country::NO), 
            "NP" => Ok(Country::NP), 
            "NR" => Ok(Country::NR), 
            "NT" => Ok(Country::NT), 
            "NU" => Ok(Country::NU), 
            "NZ" => Ok(Country::NZ), 
            "OM" => Ok(Country::OM), 
            "PA" => Ok(Country::PA), 
            "PE" => Ok(Country::PE), 
            "PF" => Ok(Country::PF), 
            "PG" => Ok(Country::PG), 
            "PH" => Ok(Country::PH), 
            "PK" => Ok(Country::PK), 
            "PL" => Ok(Country::PL), 
            "PM" => Ok(Country::PM), 
            "PN" => Ok(Country::PN), 
            "PR" => Ok(Country::PR), 
            "PT" => Ok(Country::PT), 
            "PW" => Ok(Country::PW), 
            "PY" => Ok(Country::PY), 
            "QA" => Ok(Country::QA), 
            "RE" => Ok(Country::RE), 
            "RO" => Ok(Country::RO), 
            "RU" => Ok(Country::RU), 
            "RW" => Ok(Country::RW), 
            "SA" => Ok(Country::SA), 
            "SB" => Ok(Country::SB), 
            "SC" => Ok(Country::SC), 
            "SD" => Ok(Country::SD), 
            "SE" => Ok(Country::SE), 
            "SG" => Ok(Country::SG), 
            "SH" => Ok(Country::SH), 
            "SI" => Ok(Country::SI), 
            "SJ" => Ok(Country::SJ), 
            "SK" => Ok(Country::SK), 
            "SL" => Ok(Country::SL), 
            "SM" => Ok(Country::SM), 
            "SN" => Ok(Country::SN), 
            "SO" => Ok(Country::SO), 
            "SR" => Ok(Country::SR), 
            "ST" => Ok(Country::ST), 
            "SU" => Ok(Country::SU), 
            "SV" => Ok(Country::SV), 
            "SY" => Ok(Country::SY), 
            "SZ" => Ok(Country::SZ), 
            "TC" => Ok(Country::TC), 
            "TD" => Ok(Country::TD), 
            "TF" => Ok(Country::TF), 
            "TG" => Ok(Country::TG), 
            "TH" => Ok(Country::TH), 
            "TJ" => Ok(Country::TJ), 
            "TK" => Ok(Country::TK), 
            "TM" => Ok(Country::TM), 
            "TN" => Ok(Country::TN), 
            "TO" => Ok(Country::TO), 
            "TP" => Ok(Country::TP), 
            "TR" => Ok(Country::TR), 
            "TT" => Ok(Country::TT), 
            "TV" => Ok(Country::TV), 
            "TW" => Ok(Country::TW), 
            "TZ" => Ok(Country::TZ), 
            "UA" => Ok(Country::UA), 
            "UG" => Ok(Country::UG), 
            "UM" => Ok(Country::UM), 
            "US" => Ok(Country::US), 
            "UY" => Ok(Country::UY), 
            "UZ" => Ok(Country::UZ), 
            "VA" => Ok(Country::VA), 
            "VC" => Ok(Country::VC), 
            "VE" => Ok(Country::VE), 
            "VG" => Ok(Country::VG), 
            "VI" => Ok(Country::VI), 
            "VN" => Ok(Country::VN), 
            "VU" => Ok(Country::VU), 
            "WF" => Ok(Country::WF), 
            "WS" => Ok(Country::WS), 
            "YD" => Ok(Country::YD), 
            "YE" => Ok(Country::YE), 
            "YT" => Ok(Country::YT), 
            "YU" => Ok(Country::YU), 
            "ZA" => Ok(Country::ZA), 
            "ZM" => Ok(Country::ZM), 
            "ZR" => Ok(Country::ZR), 
            "ZW" => Ok(Country::ZW), 
            "ZZ" => Ok(Country::ZZ), 
            _ => Err("Oh, no ...") 
        }
    }

    pub fn index(&self) -> u8 {
        match *self {
            Country::AD => 0, 
            Country::AE => 1, 
            Country::AF => 2, 
            Country::AG => 3, 
            Country::AI => 4, 
            Country::AL => 5, 
            Country::AM => 6, 
            Country::AN => 7, 
            Country::AO => 8, 
            Country::AQ => 9, 
            Country::AR => 10, 
            Country::AS => 11, 
            Country::AT => 12, 
            Country::AU => 13, 
            Country::AW => 14, 
            Country::AZ => 15, 
            Country::BA => 16, 
            Country::BB => 17, 
            Country::BD => 18, 
            Country::BE => 19, 
            Country::BF => 20, 
            Country::BG => 21, 
            Country::BH => 22, 
            Country::BI => 23, 
            Country::BJ => 24, 
            Country::BM => 25, 
            Country::BN => 26, 
            Country::BO => 27, 
            Country::BR => 28, 
            Country::BS => 29, 
            Country::BT => 30, 
            Country::BU => 31, 
            Country::BV => 32, 
            Country::BW => 33, 
            Country::BY => 34, 
            Country::BZ => 35, 
            Country::CA => 36, 
            Country::CC => 37, 
            Country::CF => 38, 
            Country::CG => 39, 
            Country::CH => 40, 
            Country::CI => 41, 
            Country::CK => 42, 
            Country::CL => 43, 
            Country::CM => 44, 
            Country::CN => 45, 
            Country::CO => 46, 
            Country::CR => 47, 
            Country::CS => 48, 
            Country::CU => 49, 
            Country::CV => 50, 
            Country::CX => 51, 
            Country::CY => 52, 
            Country::CZ => 53, 
            Country::DD => 54, 
            Country::DE => 55, 
            Country::DJ => 56, 
            Country::DK => 57, 
            Country::DM => 58, 
            Country::DO => 59, 
            Country::DZ => 60, 
            Country::EC => 61, 
            Country::EE => 62, 
            Country::EG => 63, 
            Country::EH => 64, 
            Country::ER => 65, 
            Country::ES => 66, 
            Country::ET => 67, 
            Country::FI => 68, 
            Country::FJ => 69, 
            Country::FK => 70, 
            Country::FM => 71, 
            Country::FO => 72, 
            Country::FR => 73, 
            Country::FX => 74, 
            Country::GA => 75, 
            Country::GB => 76, 
            Country::GD => 77, 
            Country::GE => 78, 
            Country::GF => 79, 
            Country::GH => 80, 
            Country::GI => 81, 
            Country::GL => 82, 
            Country::GM => 83, 
            Country::GN => 84, 
            Country::GP => 85, 
            Country::GQ => 86, 
            Country::GR => 87, 
            Country::GS => 88, 
            Country::GT => 89, 
            Country::GU => 90, 
            Country::GW => 91, 
            Country::GY => 92, 
            Country::HK => 93, 
            Country::HM => 94, 
            Country::HN => 95, 
            Country::HR => 96, 
            Country::HT => 97, 
            Country::HU => 98, 
            Country::ID => 99, 
            Country::IE => 100, 
            Country::IL => 101, 
            Country::IN => 102, 
            Country::IO => 103, 
            Country::IQ => 104, 
            Country::IR => 105, 
            Country::IS => 106, 
            Country::IT => 107, 
            Country::JM => 108, 
            Country::JO => 109, 
            Country::JP => 110, 
            Country::KE => 111, 
            Country::KG => 112, 
            Country::KH => 113, 
            Country::KI => 114, 
            Country::KM => 115, 
            Country::KN => 116, 
            Country::KP => 117, 
            Country::KR => 118, 
            Country::KW => 119, 
            Country::KY => 120, 
            Country::KZ => 121, 
            Country::LA => 122, 
            Country::LB => 123, 
            Country::LC => 124, 
            Country::LI => 125, 
            Country::LK => 126, 
            Country::LR => 127, 
            Country::LS => 128, 
            Country::LT => 129, 
            Country::LU => 130, 
            Country::LV => 131, 
            Country::LY => 132, 
            Country::MA => 133, 
            Country::MC => 134, 
            Country::MD => 135, 
            Country::MG => 136, 
            Country::MH => 137, 
            Country::ML => 138, 
            Country::MN => 139, 
            Country::MM => 140, 
            Country::MO => 141, 
            Country::MP => 142, 
            Country::MQ => 143, 
            Country::MR => 144, 
            Country::MS => 145, 
            Country::MT => 146, 
            Country::MU => 147, 
            Country::MV => 148, 
            Country::MW => 149, 
            Country::MX => 150, 
            Country::MY => 151, 
            Country::MZ => 152, 
            Country::NA => 153, 
            Country::NC => 154, 
            Country::NE => 155, 
            Country::NF => 156, 
            Country::NG => 157, 
            Country::NI => 158, 
            Country::NL => 159, 
            Country::NO => 160, 
            Country::NP => 161, 
            Country::NR => 162, 
            Country::NT => 163, 
            Country::NU => 164, 
            Country::NZ => 165, 
            Country::OM => 166, 
            Country::PA => 167, 
            Country::PE => 168, 
            Country::PF => 169, 
            Country::PG => 170, 
            Country::PH => 171, 
            Country::PK => 172, 
            Country::PL => 173, 
            Country::PM => 174, 
            Country::PN => 175, 
            Country::PR => 176, 
            Country::PT => 177, 
            Country::PW => 178, 
            Country::PY => 179, 
            Country::QA => 180, 
            Country::RE => 181, 
            Country::RO => 182, 
            Country::RU => 183, 
            Country::RW => 184, 
            Country::SA => 185, 
            Country::SB => 186, 
            Country::SC => 187, 
            Country::SD => 188, 
            Country::SE => 189, 
            Country::SG => 190, 
            Country::SH => 191, 
            Country::SI => 192, 
            Country::SJ => 193, 
            Country::SK => 194, 
            Country::SL => 195, 
            Country::SM => 196, 
            Country::SN => 197, 
            Country::SO => 198, 
            Country::SR => 199, 
            Country::ST => 200, 
            Country::SU => 201, 
            Country::SV => 202, 
            Country::SY => 203, 
            Country::SZ => 204, 
            Country::TC => 205, 
            Country::TD => 206, 
            Country::TF => 207, 
            Country::TG => 208, 
            Country::TH => 209, 
            Country::TJ => 210, 
            Country::TK => 211, 
            Country::TM => 212, 
            Country::TN => 213, 
            Country::TO => 214, 
            Country::TP => 215, 
            Country::TR => 216, 
            Country::TT => 217, 
            Country::TV => 218, 
            Country::TW => 219, 
            Country::TZ => 220, 
            Country::UA => 221, 
            Country::UG => 222, 
            Country::UM => 223, 
            Country::US => 224, 
            Country::UY => 225, 
            Country::UZ => 226, 
            Country::VA => 227, 
            Country::VC => 228, 
            Country::VE => 229, 
            Country::VG => 230, 
            Country::VI => 231, 
            Country::VN => 232, 
            Country::VU => 233, 
            Country::WF => 234, 
            Country::WS => 235, 
            Country::YD => 236, 
            Country::YE => 237, 
            Country::YT => 238, 
            Country::YU => 239, 
            Country::ZA => 240, 
            Country::ZM => 241, 
            Country::ZR => 242, 
            Country::ZW => 243, 
            Country::ZZ => 244, 
        }
    }

    pub fn code(&self) -> &'static str {
        match *self {
            Country::AD => "AD", 
            Country::AE => "AE", 
            Country::AF => "AF", 
            Country::AG => "AG", 
            Country::AI => "AI", 
            Country::AL => "AL", 
            Country::AM => "AM", 
            Country::AN => "AN", 
            Country::AO => "AO", 
            Country::AQ => "AQ", 
            Country::AR => "AR", 
            Country::AS => "AS", 
            Country::AT => "AT", 
            Country::AU => "AU", 
            Country::AW => "AW", 
            Country::AZ => "AZ", 
            Country::BA => "BA", 
            Country::BB => "BB", 
            Country::BD => "BD", 
            Country::BE => "BE", 
            Country::BF => "BF", 
            Country::BG => "BG", 
            Country::BH => "BH", 
            Country::BI => "BI", 
            Country::BJ => "BJ", 
            Country::BM => "BM", 
            Country::BN => "BN", 
            Country::BO => "BO", 
            Country::BR => "BR", 
            Country::BS => "BS", 
            Country::BT => "BT", 
            Country::BU => "BU", 
            Country::BV => "BV", 
            Country::BW => "BW", 
            Country::BY => "BY", 
            Country::BZ => "BZ", 
            Country::CA => "CA", 
            Country::CC => "CC", 
            Country::CF => "CF", 
            Country::CG => "CG", 
            Country::CH => "CH", 
            Country::CI => "CI", 
            Country::CK => "CK", 
            Country::CL => "CL", 
            Country::CM => "CM", 
            Country::CN => "CN", 
            Country::CO => "CO", 
            Country::CR => "CR", 
            Country::CS => "CS", 
            Country::CU => "CU", 
            Country::CV => "CV", 
            Country::CX => "CX", 
            Country::CY => "CY", 
            Country::CZ => "CZ", 
            Country::DD => "DD", 
            Country::DE => "DE", 
            Country::DJ => "DJ", 
            Country::DK => "DK", 
            Country::DM => "DM", 
            Country::DO => "DO", 
            Country::DZ => "DZ", 
            Country::EC => "EC", 
            Country::EE => "EE", 
            Country::EG => "EG", 
            Country::EH => "EH", 
            Country::ER => "ER", 
            Country::ES => "ES", 
            Country::ET => "ET", 
            Country::FI => "FI", 
            Country::FJ => "FJ", 
            Country::FK => "FK", 
            Country::FM => "FM", 
            Country::FO => "FO", 
            Country::FR => "FR", 
            Country::FX => "FX", 
            Country::GA => "GA", 
            Country::GB => "GB", 
            Country::GD => "GD", 
            Country::GE => "GE", 
            Country::GF => "GF", 
            Country::GH => "GH", 
            Country::GI => "GI", 
            Country::GL => "GL", 
            Country::GM => "GM", 
            Country::GN => "GN", 
            Country::GP => "GP", 
            Country::GQ => "GQ", 
            Country::GR => "GR", 
            Country::GS => "GS", 
            Country::GT => "GT", 
            Country::GU => "GU", 
            Country::GW => "GW", 
            Country::GY => "GY", 
            Country::HK => "HK", 
            Country::HM => "HM", 
            Country::HN => "HN", 
            Country::HR => "HR", 
            Country::HT => "HT", 
            Country::HU => "HU", 
            Country::ID => "ID", 
            Country::IE => "IE", 
            Country::IL => "IL", 
            Country::IN => "IN", 
            Country::IO => "IO", 
            Country::IQ => "IQ", 
            Country::IR => "IR", 
            Country::IS => "IS", 
            Country::IT => "IT", 
            Country::JM => "JM", 
            Country::JO => "JO", 
            Country::JP => "JP", 
            Country::KE => "KE", 
            Country::KG => "KG", 
            Country::KH => "KH", 
            Country::KI => "KI", 
            Country::KM => "KM", 
            Country::KN => "KN", 
            Country::KP => "KP", 
            Country::KR => "KR", 
            Country::KW => "KW", 
            Country::KY => "KY", 
            Country::KZ => "KZ", 
            Country::LA => "LA", 
            Country::LB => "LB", 
            Country::LC => "LC", 
            Country::LI => "LI", 
            Country::LK => "LK", 
            Country::LR => "LR", 
            Country::LS => "LS", 
            Country::LT => "LT", 
            Country::LU => "LU", 
            Country::LV => "LV", 
            Country::LY => "LY", 
            Country::MA => "MA", 
            Country::MC => "MC", 
            Country::MD => "MD", 
            Country::MG => "MG", 
            Country::MH => "MH", 
            Country::ML => "ML", 
            Country::MN => "MN", 
            Country::MM => "MM", 
            Country::MO => "MO", 
            Country::MP => "MP", 
            Country::MQ => "MQ", 
            Country::MR => "MR", 
            Country::MS => "MS", 
            Country::MT => "MT", 
            Country::MU => "MU", 
            Country::MV => "MV", 
            Country::MW => "MW", 
            Country::MX => "MX", 
            Country::MY => "MY", 
            Country::MZ => "MZ", 
            Country::NA => "NA", 
            Country::NC => "NC", 
            Country::NE => "NE", 
            Country::NF => "NF", 
            Country::NG => "NG", 
            Country::NI => "NI", 
            Country::NL => "NL", 
            Country::NO => "NO", 
            Country::NP => "NP", 
            Country::NR => "NR", 
            Country::NT => "NT", 
            Country::NU => "NU", 
            Country::NZ => "NZ", 
            Country::OM => "OM", 
            Country::PA => "PA", 
            Country::PE => "PE", 
            Country::PF => "PF", 
            Country::PG => "PG", 
            Country::PH => "PH", 
            Country::PK => "PK", 
            Country::PL => "PL", 
            Country::PM => "PM", 
            Country::PN => "PN", 
            Country::PR => "PR", 
            Country::PT => "PT", 
            Country::PW => "PW", 
            Country::PY => "PY", 
            Country::QA => "QA", 
            Country::RE => "RE", 
            Country::RO => "RO", 
            Country::RU => "RU", 
            Country::RW => "RW", 
            Country::SA => "SA", 
            Country::SB => "SB", 
            Country::SC => "SC", 
            Country::SD => "SD", 
            Country::SE => "SE", 
            Country::SG => "SG", 
            Country::SH => "SH", 
            Country::SI => "SI", 
            Country::SJ => "SJ", 
            Country::SK => "SK", 
            Country::SL => "SL", 
            Country::SM => "SM", 
            Country::SN => "SN", 
            Country::SO => "SO", 
            Country::SR => "SR", 
            Country::ST => "ST", 
            Country::SU => "SU", 
            Country::SV => "SV", 
            Country::SY => "SY", 
            Country::SZ => "SZ", 
            Country::TC => "TC", 
            Country::TD => "TD", 
            Country::TF => "TF", 
            Country::TG => "TG", 
            Country::TH => "TH", 
            Country::TJ => "TJ", 
            Country::TK => "TK", 
            Country::TM => "TM", 
            Country::TN => "TN", 
            Country::TO => "TO", 
            Country::TP => "TP", 
            Country::TR => "TR", 
            Country::TT => "TT", 
            Country::TV => "TV", 
            Country::TW => "TW", 
            Country::TZ => "TZ", 
            Country::UA => "UA", 
            Country::UG => "UG", 
            Country::UM => "UM", 
            Country::US => "US", 
            Country::UY => "UY", 
            Country::UZ => "UZ", 
            Country::VA => "VA", 
            Country::VC => "VC", 
            Country::VE => "VE", 
            Country::VG => "VG", 
            Country::VI => "VI", 
            Country::VN => "VN", 
            Country::VU => "VU", 
            Country::WF => "WF", 
            Country::WS => "WS", 
            Country::YD => "YD", 
            Country::YE => "YE", 
            Country::YT => "YT", 
            Country::YU => "YU", 
            Country::ZA => "ZA", 
            Country::ZM => "ZM", 
            Country::ZR => "ZR", 
            Country::ZW => "ZW", 
            Country::ZZ => "ZZ", 
        }
    }

    pub fn description(&self) -> &'static str {
        match *self {
            Country::AD => "Andorra", 
            Country::AE => "United Arab Emirates", 
            Country::AF => "Afghanistan", 
            Country::AG => "Antigua & Barbuda", 
            Country::AI => "Anguilla", 
            Country::AL => "Albania", 
            Country::AM => "Armenia", 
            Country::AN => "Netherlands Antilles", 
            Country::AO => "Angola", 
            Country::AQ => "Antarctica", 
            Country::AR => "Argentina", 
            Country::AS => "American Samoa", 
            Country::AT => "Austria", 
            Country::AU => "Australia", 
            Country::AW => "Aruba", 
            Country::AZ => "Azerbaijan", 
            Country::BA => "Bosnia and Herzegovina", 
            Country::BB => "Barbados", 
            Country::BD => "Bangladesh", 
            Country::BE => "Belgium", 
            Country::BF => "Burkina Faso", 
            Country::BG => "Bulgaria", 
            Country::BH => "Bahrain", 
            Country::BI => "Burundi", 
            Country::BJ => "Benin", 
            Country::BM => "Bermuda", 
            Country::BN => "Brunei Darussalam", 
            Country::BO => "Bolivia", 
            Country::BR => "Brazil", 
            Country::BS => "Bahama", 
            Country::BT => "Bhutan", 
            Country::BU => "Burma (no longer exists)", 
            Country::BV => "Bouvet Island", 
            Country::BW => "Botswana", 
            Country::BY => "Belarus", 
            Country::BZ => "Belize", 
            Country::CA => "Canada", 
            Country::CC => "Cocos (Keeling) Islands", 
            Country::CF => "Central African Republic", 
            Country::CG => "Congo", 
            Country::CH => "Switzerland", 
            Country::CI => "Côte D'ivoire (Ivory Coast)", 
            Country::CK => "Cook Iislands", 
            Country::CL => "Chile", 
            Country::CM => "Cameroon", 
            Country::CN => "China", 
            Country::CO => "Colombia", 
            Country::CR => "Costa Rica", 
            Country::CS => "Czechoslovakia (no longer exists)", 
            Country::CU => "Cuba", 
            Country::CV => "Cape Verde", 
            Country::CX => "Christmas Island", 
            Country::CY => "Cyprus", 
            Country::CZ => "Czech Republic", 
            Country::DD => "German Democratic Republic (no longer exists)", 
            Country::DE => "Germany", 
            Country::DJ => "Djibouti", 
            Country::DK => "Denmark", 
            Country::DM => "Dominica", 
            Country::DO => "Dominican Republic", 
            Country::DZ => "Algeria", 
            Country::EC => "Ecuador", 
            Country::EE => "Estonia", 
            Country::EG => "Egypt", 
            Country::EH => "Western Sahara", 
            Country::ER => "Eritrea", 
            Country::ES => "Spain", 
            Country::ET => "Ethiopia", 
            Country::FI => "Finland", 
            Country::FJ => "Fiji", 
            Country::FK => "Falkland Islands (Malvinas)", 
            Country::FM => "Micronesia", 
            Country::FO => "Faroe Islands", 
            Country::FR => "France", 
            Country::FX => "France, Metropolitan", 
            Country::GA => "Gabon", 
            Country::GB => "United Kingdom (Great Britain)", 
            Country::GD => "Grenada", 
            Country::GE => "Georgia", 
            Country::GF => "French Guiana", 
            Country::GH => "Ghana", 
            Country::GI => "Gibraltar", 
            Country::GL => "Greenland", 
            Country::GM => "Gambia", 
            Country::GN => "Guinea", 
            Country::GP => "Guadeloupe", 
            Country::GQ => "Equatorial Guinea", 
            Country::GR => "Greece", 
            Country::GS => "South Georgia and the South Sandwich Islands", 
            Country::GT => "Guatemala", 
            Country::GU => "Guam", 
            Country::GW => "Guinea-Bissau", 
            Country::GY => "Guyana", 
            Country::HK => "Hong Kong", 
            Country::HM => "Heard & McDonald Islands", 
            Country::HN => "Honduras", 
            Country::HR => "Croatia", 
            Country::HT => "Haiti", 
            Country::HU => "Hungary", 
            Country::ID => "Indonesia", 
            Country::IE => "Ireland", 
            Country::IL => "Israel", 
            Country::IN => "India", 
            Country::IO => "British Indian Ocean Territory", 
            Country::IQ => "Iraq", 
            Country::IR => "Islamic Republic of Iran", 
            Country::IS => "Iceland", 
            Country::IT => "Italy", 
            Country::JM => "Jamaica", 
            Country::JO => "Jordan", 
            Country::JP => "Japan", 
            Country::KE => "Kenya", 
            Country::KG => "Kyrgyzstan", 
            Country::KH => "Cambodia", 
            Country::KI => "Kiribati", 
            Country::KM => "Comoros", 
            Country::KN => "St. Kitts and Nevis", 
            Country::KP => "Korea, Democratic People's Republic of", 
            Country::KR => "Korea, Republic of", 
            Country::KW => "Kuwait", 
            Country::KY => "Cayman Islands", 
            Country::KZ => "Kazakhstan", 
            Country::LA => "Lao People's Democratic Republic", 
            Country::LB => "Lebanon", 
            Country::LC => "Saint Lucia", 
            Country::LI => "Liechtenstein", 
            Country::LK => "Sri Lanka", 
            Country::LR => "Liberia", 
            Country::LS => "Lesotho", 
            Country::LT => "Lithuania", 
            Country::LU => "Luxembourg", 
            Country::LV => "Latvia", 
            Country::LY => "Libyan Arab Jamahiriya", 
            Country::MA => "Morocco", 
            Country::MC => "Monaco", 
            Country::MD => "Moldova, Republic of", 
            Country::MG => "Madagascar", 
            Country::MH => "Marshall Islands", 
            Country::ML => "Mali", 
            Country::MN => "Mongolia", 
            Country::MM => "Myanmar", 
            Country::MO => "Macau", 
            Country::MP => "Northern Mariana Islands", 
            Country::MQ => "Martinique", 
            Country::MR => "Mauritania", 
            Country::MS => "Monserrat", 
            Country::MT => "Malta", 
            Country::MU => "Mauritius", 
            Country::MV => "Maldives", 
            Country::MW => "Malawi", 
            Country::MX => "Mexico", 
            Country::MY => "Malaysia", 
            Country::MZ => "Mozambique", 
            Country::NA => "Namibia", 
            Country::NC => "New Caledonia", 
            Country::NE => "Niger", 
            Country::NF => "Norfolk Island", 
            Country::NG => "Nigeria", 
            Country::NI => "Nicaragua", 
            Country::NL => "Netherlands", 
            Country::NO => "Norway", 
            Country::NP => "Nepal", 
            Country::NR => "Nauru", 
            Country::NT => "Neutral Zone (no longer exists)", 
            Country::NU => "Niue", 
            Country::NZ => "New Zealand", 
            Country::OM => "Oman", 
            Country::PA => "Panama", 
            Country::PE => "Peru", 
            Country::PF => "French Polynesia", 
            Country::PG => "Papua New Guinea", 
            Country::PH => "Philippines", 
            Country::PK => "Pakistan", 
            Country::PL => "Poland", 
            Country::PM => "St. Pierre & Miquelon", 
            Country::PN => "Pitcairn", 
            Country::PR => "Puerto Rico", 
            Country::PT => "Portugal", 
            Country::PW => "Palau", 
            Country::PY => "Paraguay", 
            Country::QA => "Qatar", 
            Country::RE => "Réunion", 
            Country::RO => "Romania", 
            Country::RU => "Russian Federation", 
            Country::RW => "Rwanda", 
            Country::SA => "Saudi Arabia", 
            Country::SB => "Solomon Islands", 
            Country::SC => "Seychelles", 
            Country::SD => "Sudan", 
            Country::SE => "Sweden", 
            Country::SG => "Singapore", 
            Country::SH => "St. Helena", 
            Country::SI => "Slovenia", 
            Country::SJ => "Svalbard & Jan Mayen Islands", 
            Country::SK => "Slovakia", 
            Country::SL => "Sierra Leone", 
            Country::SM => "San Marino", 
            Country::SN => "Senegal", 
            Country::SO => "Somalia", 
            Country::SR => "Suriname", 
            Country::ST => "Sao Tome & Principe", 
            Country::SU => "Union of Soviet Socialist Republics (no longer exists)", 
            Country::SV => "El Salvador", 
            Country::SY => "Syrian Arab Republic", 
            Country::SZ => "Swaziland", 
            Country::TC => "Turks & Caicos Islands", 
            Country::TD => "Chad", 
            Country::TF => "French Southern Territories", 
            Country::TG => "Togo", 
            Country::TH => "Thailand", 
            Country::TJ => "Tajikistan", 
            Country::TK => "Tokelau", 
            Country::TM => "Turkmenistan", 
            Country::TN => "Tunisia", 
            Country::TO => "Tonga", 
            Country::TP => "East Timor", 
            Country::TR => "Turkey", 
            Country::TT => "Trinidad & Tobago", 
            Country::TV => "Tuvalu", 
            Country::TW => "Taiwan, Province of China", 
            Country::TZ => "Tanzania, United Republic of", 
            Country::UA => "Ukraine", 
            Country::UG => "Uganda", 
            Country::UM => "United States Minor Outlying Islands", 
            Country::US => "United States of America", 
            Country::UY => "Uruguay", 
            Country::UZ => "Uzbekistan", 
            Country::VA => "Vatican City State (Holy See)", 
            Country::VC => "St. Vincent & the Grenadines", 
            Country::VE => "Venezuela", 
            Country::VG => "British Virgin Islands", 
            Country::VI => "United States Virgin Islands", 
            Country::VN => "Viet Nam", 
            Country::VU => "Vanuatu", 
            Country::WF => "Wallis & Futuna Islands", 
            Country::WS => "Samoa", 
            Country::YD => "Democratic Yemen (no longer exists)", 
            Country::YE => "Yemen", 
            Country::YT => "Mayotte", 
            Country::YU => "Yugoslavia", 
            Country::ZA => "South Africa", 
            Country::ZM => "Zambia", 
            Country::ZR => "Zaire", 
            Country::ZW => "Zimbabwe", 
            Country::ZZ => "Unknown or unspecified country", 
        }
    }
}

